import {
  ActivityItem,
  Client,
  ContentTrend,
  Invoice,
  Lead,
  LinkedInPost,
  MonthlyFinance,
  Project,
  TeamMember,
  TweetQueueItem,
  TweetTemplate,
} from "@/lib/types";

export const clients: Client[] = [
  {
    id: "healthy-chef",
    company: "Healthy Chef",
    initials: "HC",
    contactName: "Arjun",
    contactEmail: "arjun@healthychef.in",
    contactPhone: "+91 98765 10001",
    status: "Active",
    monthlyRetainer: 200000,
    videosDelivered: 6,
    videosTarget: 8,
    nextShootDate: "2026-03-19",
    lastPaymentStatus: "Pending",
    totalRevenue: 2400000,
    satisfactionScore: 4.6,
    notes: "Nutrition-first brand storytelling and performance creatives.",
  },
  {
    id: "broke-college-kid",
    company: "Broke College Kid",
    initials: "BK",
    contactName: "Alisha",
    contactEmail: "alisha@brokecollegekid.in",
    contactPhone: "+91 98765 10002",
    status: "Active",
    monthlyRetainer: 150000,
    videosDelivered: 7,
    videosTarget: 8,
    nextShootDate: "2026-03-23",
    lastPaymentStatus: "Paid",
    totalRevenue: 1800000,
    satisfactionScore: 4.8,
    notes: "Youth-focused content engine with short-form viral hooks.",
  },
  {
    id: "morph",
    company: "Morph",
    initials: "MO",
    contactName: "Anirudh",
    contactEmail: "anirudh@morph.in",
    contactPhone: "+91 98765 10003",
    status: "Active",
    monthlyRetainer: 125000,
    videosDelivered: 5,
    videosTarget: 6,
    nextShootDate: "2026-03-22",
    lastPaymentStatus: "Paid",
    totalRevenue: 1500000,
    satisfactionScore: 4.9,
    notes: "Product storytelling and launch narratives.",
  },
  {
    id: "playgram",
    company: "Playgram",
    initials: "PG",
    contactName: "Alwin",
    contactEmail: "alwin@playgram.in",
    contactPhone: "+91 98765 10004",
    status: "Active",
    monthlyRetainer: 175000,
    videosDelivered: 4,
    videosTarget: 8,
    nextShootDate: "2026-03-21",
    lastPaymentStatus: "Overdue",
    totalRevenue: 2100000,
    satisfactionScore: 4.4,
    notes: "Gaming and creator lifestyle campaigns.",
  },
  {
    id: "whensheswipedright",
    company: "Whensheswipedright",
    initials: "WS",
    contactName: "Sahishana",
    contactEmail: "sahishana@whensheswipedright.in",
    contactPhone: "+91 98765 10005",
    status: "Active",
    monthlyRetainer: 100000,
    videosDelivered: 3,
    videosTarget: 5,
    nextShootDate: "2026-03-25",
    lastPaymentStatus: "Pending",
    totalRevenue: 1200000,
    satisfactionScore: 4.3,
    notes: "Lifestyle-first storytelling and episodic reels.",
  },
  {
    id: "dream-a-dozen",
    company: "Dream A Dozen",
    initials: "DD",
    contactName: "Venkataswaran",
    contactEmail: "vk@dreamadozen.in",
    contactPhone: "+91 98765 10006",
    status: "Paused",
    monthlyRetainer: 250000,
    videosDelivered: 1,
    videosTarget: 6,
    nextShootDate: "2026-04-02",
    lastPaymentStatus: "Paid",
    totalRevenue: 3000000,
    satisfactionScore: 4.5,
    notes: "Premium ad films and creator partnerships.",
  },
  {
    id: "freshworks",
    company: "Freshworks",
    initials: "FW",
    contactName: "Priya Sharma",
    contactEmail: "priya@freshworks.in",
    contactPhone: "+91 98765 10007",
    status: "Active",
    monthlyRetainer: 180000,
    videosDelivered: 6,
    videosTarget: 7,
    nextShootDate: "2026-03-24",
    lastPaymentStatus: "Paid",
    totalRevenue: 2160000,
    satisfactionScore: 4.7,
    notes: "Thought leadership and product education videos.",
  },
  {
    id: "notion-india",
    company: "Notion India",
    initials: "NI",
    contactName: "Anjali Gupta",
    contactEmail: "anjali@notionindia.in",
    contactPhone: "+91 98765 10008",
    status: "Completed",
    monthlyRetainer: 300000,
    videosDelivered: 10,
    videosTarget: 10,
    nextShootDate: "2026-03-01",
    lastPaymentStatus: "Paid",
    totalRevenue: 3600000,
    satisfactionScore: 4.9,
    notes: "Campaign closed successfully with premium brand films.",
  },
];

export const projects: Project[] = [
  { id: "p1", name: "Morph Brand Launch Reel", clientId: "morph", clientName: "Morph", editorName: "Anirudh", editorInitials: "AN", dueDate: "Mar 19", status: "Editing", priority: "High", progress: 70 },
  { id: "p2", name: "Playgram Creator Campaign Cut", clientId: "playgram", clientName: "Playgram", editorName: "Alwin", editorInitials: "AL", dueDate: "Mar 21", status: "Review", priority: "High", progress: 86 },
  { id: "p3", name: "Whensheswipedright Episode Teaser", clientId: "whensheswipedright", clientName: "Whensheswipedright", editorName: "Sahishana", editorInitials: "SA", dueDate: "Mar 22", status: "Editing", priority: "Medium", progress: 62 },
  { id: "p4", name: "Dream A Dozen Premium Ad Film", clientId: "dream-a-dozen", clientName: "Dream A Dozen", editorName: "Arjun", editorInitials: "AR", dueDate: "Mar 20", status: "Shooting", priority: "Medium", progress: 28 },
  { id: "p5", name: "Healthy Chef Meal Story Reel", clientId: "healthy-chef", clientName: "Healthy Chef", editorName: "Alisha", editorInitials: "AI", dueDate: "Mar 25", status: "Editing", priority: "Low", progress: 40 },
  { id: "p6", name: "Broke College Kid Street Vox Pop", clientId: "broke-college-kid", clientName: "Broke College Kid", editorName: "Venkataswaran", editorInitials: "VK", dueDate: "Mar 24", status: "Review", priority: "Medium", progress: 80 },
  { id: "p7", name: "Morph Product Demo Cut", clientId: "morph", clientName: "Morph", editorName: "Anirudh", editorInitials: "AN", dueDate: "Mar 28", status: "Shooting", priority: "Low", progress: 18 },
  { id: "p8", name: "Playgram Challenge Video", clientId: "playgram", clientName: "Playgram", editorName: "Alwin", editorInitials: "AL", dueDate: "Mar 29", status: "Delivered", priority: "Medium", progress: 100 },
  { id: "p9", name: "Whensheswipedright Trailer Cut", clientId: "whensheswipedright", clientName: "Whensheswipedright", editorName: "Sahishana", editorInitials: "SA", dueDate: "Mar 26", status: "Delivered", priority: "High", progress: 100 },
  { id: "p10", name: "Dream A Dozen Behind The Scenes", clientId: "dream-a-dozen", clientName: "Dream A Dozen", editorName: "Arjun", editorInitials: "AR", dueDate: "Mar 30", status: "Editing", priority: "Low", progress: 52 },
  { id: "p11", name: "Healthy Chef Testimonial Film", clientId: "healthy-chef", clientName: "Healthy Chef", editorName: "Alisha", editorInitials: "AI", dueDate: "Apr 04", status: "Review", priority: "High", progress: 74 },
  { id: "p12", name: "Broke College Kid Campus Reel", clientId: "broke-college-kid", clientName: "Broke College Kid", editorName: "Venkataswaran", editorInitials: "VK", dueDate: "Apr 01", status: "Shooting", priority: "Medium", progress: 24 },
  { id: "p13", name: "Freshworks Q1 Brand Reel", clientId: "freshworks", clientName: "Freshworks", editorName: "Anirudh", editorInitials: "AN", dueDate: "Mar 14", status: "Delivered", priority: "Low", progress: 100 },
  { id: "p14", name: "Notion India Workspace Tips", clientId: "notion-india", clientName: "Notion India", editorName: "Alwin", editorInitials: "AL", dueDate: "Apr 03", status: "Shooting", priority: "Medium", progress: 30 },
  { id: "p15", name: "Morph Founder AMA Teaser", clientId: "morph", clientName: "Morph", editorName: "Sahishana", editorInitials: "SA", dueDate: "Apr 02", status: "Editing", priority: "High", progress: 63 },
  { id: "p16", name: "Playgram Use-Case Montage", clientId: "playgram", clientName: "Playgram", editorName: "Arjun", editorInitials: "AR", dueDate: "Apr 05", status: "Review", priority: "Medium", progress: 81 },
];

export const teamMembers: TeamMember[] = [
  { id: "t1", name: "Anirudh", initials: "AN", role: "Senior Editor", status: "In Edit", videosPerWeek: 12, avgEditHours: 2.8, currentAssignment: "Editing Morph Brand Launch Reel", output7Days: [2, 1, 2, 2, 1, 2, 2] },
  { id: "t2", name: "Sahishana", initials: "SA", role: "Motion Designer", status: "In Edit", videosPerWeek: 8, avgEditHours: 3.5, currentAssignment: "Whensheswipedright Episode Teaser", output7Days: [1, 1, 2, 1, 1, 1, 1] },
  { id: "t3", name: "Alwin", initials: "AL", role: "Editor", status: "Available", videosPerWeek: 10, avgEditHours: 3.1, currentAssignment: "Playgram Creator Campaign Cut", output7Days: [1, 2, 1, 2, 1, 2, 1] },
  { id: "t4", name: "Arjun", initials: "AR", role: "Cinematographer", status: "On Shoot", videosPerWeek: 6, avgEditHours: 0, currentAssignment: "Dream A Dozen Ad Film Shoot", output7Days: [1, 0, 1, 0, 1, 1, 1] },
  { id: "t5", name: "Alisha", initials: "AI", role: "Junior Editor", status: "In Edit", videosPerWeek: 7, avgEditHours: 3.8, currentAssignment: "Healthy Chef Meal Story Reel", output7Days: [1, 1, 1, 1, 1, 1, 1] },
  { id: "t6", name: "Venkataswaran", initials: "VK", role: "Creative Director", status: "Available", videosPerWeek: 9, avgEditHours: 2.9, currentAssignment: "Reviewing weekly client delivery queue", output7Days: [1, 2, 1, 1, 2, 1, 1] },
];

export const invoices: Invoice[] = [
  { id: "i1", invoiceNo: "INV-028", clientId: "freshworks", clientName: "Freshworks", amount: 200000, dateIssued: "Mar 01", dueDate: "Mar 15", status: "Overdue", description: "March retainer" },
  { id: "i2", invoiceNo: "INV-027", clientId: "scaleup-ai", clientName: "ScaleUp AI", amount: 175000, dateIssued: "Mar 01", dueDate: "Mar 15", status: "Pending", description: "March retainer" },
  { id: "i3", invoiceNo: "INV-026", clientId: "zomato-creators", clientName: "Zomato Creators", amount: 150000, dateIssued: "Feb 28", dueDate: "Mar 14", status: "Paid", description: "Monthly content retainer" },
  { id: "i4", invoiceNo: "INV-025", clientId: "brightpath-education", clientName: "BrightPath", amount: 125000, dateIssued: "Feb 25", dueDate: "Mar 10", status: "Paid", description: "Educational content package" },
  { id: "i5", invoiceNo: "INV-024", clientId: "notion-india", clientName: "Notion India", amount: 180000, dateIssued: "Feb 25", dueDate: "Mar 12", status: "Paid", description: "Thought leadership campaign" },
  { id: "i6", invoiceNo: "INV-023", clientId: "urbanclap-studios", clientName: "UrbanClap Studios", amount: 100000, dateIssued: "Feb 24", dueDate: "Mar 11", status: "Pending", description: "Reel production package" },
  { id: "i7", invoiceNo: "INV-022", clientId: "cred-creators", clientName: "Cred Creators", amount: 300000, dateIssued: "Feb 20", dueDate: "Mar 08", status: "Paid", description: "Premium brand film" },
  { id: "i8", invoiceNo: "INV-021", clientId: "razorpay-brand", clientName: "Razorpay Brand", amount: 250000, dateIssued: "Feb 18", dueDate: "Mar 05", status: "Paid", description: "Quarterly campaign installment" },
  { id: "i9", invoiceNo: "INV-020", clientId: "freshworks", clientName: "Freshworks", amount: 200000, dateIssued: "Feb 01", dueDate: "Feb 15", status: "Paid", description: "February retainer" },
  { id: "i10", invoiceNo: "INV-019", clientId: "scaleup-ai", clientName: "ScaleUp AI", amount: 175000, dateIssued: "Feb 01", dueDate: "Feb 15", status: "Overdue", description: "February retainer" },
  { id: "i11", invoiceNo: "INV-018", clientId: "zomato-creators", clientName: "Zomato Creators", amount: 150000, dateIssued: "Jan 31", dueDate: "Feb 14", status: "Paid", description: "January retainer" },
  { id: "i12", invoiceNo: "INV-017", clientId: "brightpath-education", clientName: "BrightPath", amount: 125000, dateIssued: "Jan 28", dueDate: "Feb 12", status: "Paid", description: "January retainer" },
  { id: "i13", invoiceNo: "INV-016", clientId: "notion-india", clientName: "Notion India", amount: 180000, dateIssued: "Jan 28", dueDate: "Feb 12", status: "Paid", description: "January strategy pack" },
  { id: "i14", invoiceNo: "INV-015", clientId: "urbanclap-studios", clientName: "UrbanClap Studios", amount: 100000, dateIssued: "Jan 26", dueDate: "Feb 10", status: "Overdue", description: "January production retainers" },
  { id: "i15", invoiceNo: "INV-014", clientId: "cred-creators", clientName: "Cred Creators", amount: 300000, dateIssued: "Jan 22", dueDate: "Feb 07", status: "Paid", description: "Final campaign wrap" },
  { id: "i16", invoiceNo: "INV-013", clientId: "freshworks", clientName: "Freshworks", amount: 220000, dateIssued: "Mar 05", dueDate: "Mar 20", status: "Draft", description: "Additional ad cutdowns" },
  { id: "i17", invoiceNo: "INV-012", clientId: "scaleup-ai", clientName: "ScaleUp AI", amount: 85000, dateIssued: "Mar 06", dueDate: "Mar 21", status: "Draft", description: "Urgent campaign edit surcharge" },
  { id: "i18", invoiceNo: "INV-011", clientId: "zomato-creators", clientName: "Zomato Creators", amount: 95000, dateIssued: "Mar 06", dueDate: "Mar 21", status: "Pending", description: "Event recap reels" },
  { id: "i19", invoiceNo: "INV-010", clientId: "notion-india", clientName: "Notion India", amount: 140000, dateIssued: "Mar 08", dueDate: "Mar 23", status: "Pending", description: "Creator collaboration edits" },
  { id: "i20", invoiceNo: "INV-009", clientId: "urbanclap-studios", clientName: "UrbanClap Studios", amount: 65000, dateIssued: "Mar 08", dueDate: "Mar 23", status: "Draft", description: "Testimonial short-form package" },
  { id: "i21", invoiceNo: "INV-008", clientId: "brightpath-education", clientName: "BrightPath", amount: 118000, dateIssued: "Mar 09", dueDate: "Mar 24", status: "Pending", description: "Course launch teaser sprint" },
];

export const monthlyFinance: MonthlyFinance[] = [
  { month: "Oct", revenue: 980000, expenses: 410000, profit: 570000 },
  { month: "Nov", revenue: 1120000, expenses: 430000, profit: 690000 },
  { month: "Dec", revenue: 1210000, expenses: 465000, profit: 745000 },
  { month: "Jan", revenue: 1180000, expenses: 472000, profit: 708000 },
  { month: "Feb", revenue: 1245000, expenses: 480000, profit: 765000 },
  { month: "Mar", revenue: 1320000, expenses: 505000, profit: 815000 },
];

export const leads: Lead[] = [
  { id: "l1", name: "Arun Prakash", company: "TechVentures", email: "arun@tv.co", status: "Replied", lastContact: "2 days ago", score: "Hot" },
  { id: "l2", name: "Maya Krishnan", company: "FinLeap", email: "maya@fl.in", status: "Opened", lastContact: "1 day ago", score: "Warm" },
  { id: "l3", name: "Sanjay Patel", company: "CloudFirst", email: "sanjay@cf.io", status: "Sent", lastContact: "3 days ago", score: "Cold" },
  { id: "l4", name: "Nisha Reddy", company: "PulseCare", email: "nisha@pulsecare.in", status: "Meeting", lastContact: "Today", score: "Hot" },
  { id: "l5", name: "Harsh Kulkarni", company: "OpsPilot", email: "harsh@opspilot.ai", status: "Opened", lastContact: "2 days ago", score: "Warm" },
  { id: "l6", name: "Priyanka Das", company: "RetailStack", email: "priyanka@retailstack.in", status: "New", lastContact: "Never", score: "New" },
  { id: "l7", name: "Kunal Bansal", company: "GrowthDock", email: "kunal@growthdock.in", status: "Sent", lastContact: "5 days ago", score: "Cold" },
  { id: "l8", name: "Farah Khan", company: "Insightly Labs", email: "farah@insightlylabs.ai", status: "Opened", lastContact: "1 day ago", score: "Warm" },
  { id: "l9", name: "Abhishek Jain", company: "Trekly", email: "abhishek@trekly.in", status: "Replied", lastContact: "4 hours ago", score: "Hot" },
  { id: "l10", name: "Ritika Menon", company: "NeoPay", email: "ritika@neopay.in", status: "Sent", lastContact: "2 days ago", score: "Cold" },
  { id: "l11", name: "Dev Malhotra", company: "Clarity Health", email: "dev@clarityhealth.in", status: "New", lastContact: "Never", score: "New" },
  { id: "l12", name: "Ishaan Goyal", company: "BuildGrid", email: "ishaan@buildgrid.in", status: "Opened", lastContact: "1 day ago", score: "Warm" },
  { id: "l13", name: "Lavanya S", company: "PeopleFlow", email: "lavanya@peopleflow.in", status: "Meeting", lastContact: "Today", score: "Hot" },
  { id: "l14", name: "Rohit Nanda", company: "FleetOS", email: "rohit@fleetos.in", status: "Sent", lastContact: "2 days ago", score: "Cold" },
  { id: "l15", name: "Ananya V", company: "ClipCart", email: "ananya@clipcart.in", status: "Opened", lastContact: "5 hours ago", score: "Warm" },
  { id: "l16", name: "Yash Agarwal", company: "SmartLedger", email: "yash@smartledger.in", status: "Replied", lastContact: "1 day ago", score: "Hot" },
  { id: "l17", name: "Shruti Rao", company: "EduMosaic", email: "shruti@edumosaic.in", status: "Sent", lastContact: "3 days ago", score: "Cold" },
  { id: "l18", name: "Manav Arora", company: "D2C Pulse", email: "manav@d2cpulse.in", status: "New", lastContact: "Never", score: "New" },
  { id: "l19", name: "Apoorva N", company: "RideWave", email: "apoorva@ridewave.in", status: "Opened", lastContact: "9 hours ago", score: "Warm" },
  { id: "l20", name: "Gaurav Shah", company: "AstraX", email: "gaurav@astrax.ai", status: "Won", lastContact: "Today", score: "Hot" },
  { id: "l21", name: "Pooja I", company: "FoundryOps", email: "pooja@foundryops.in", status: "Won", lastContact: "Today", score: "Hot" },
];

export const trendingContent: ContentTrend[] = [
  { id: "c1", platform: "LinkedIn", preview: "3 mistakes founders make while hiring video teams and how to avoid burn.", likes: 1420, shares: 240, comments: 86, viralScore: 8.8, nicheTag: "#founders" },
  { id: "c2", platform: "Instagram", preview: "Behind the scenes: how one 30-second reel drove 120 demo bookings.", likes: 9800, shares: 1220, comments: 340, viralScore: 9.1, nicheTag: "#storytelling" },
  { id: "c3", platform: "X", preview: "Unpopular opinion: your first 50 videos should be ugly, fast, and useful.", likes: 2460, shares: 520, comments: 180, viralScore: 8.7, nicheTag: "#business" },
  { id: "c4", platform: "YouTube", preview: "Case study: scaling a B2B channel from 0 to 100K with founder POV videos.", likes: 6200, shares: 880, comments: 510, viralScore: 9.3, nicheTag: "#AI" },
  { id: "c5", platform: "LinkedIn", preview: "How to build a content engine when your team is only 4 people.", likes: 1180, shares: 210, comments: 62, viralScore: 8.2, nicheTag: "#business" },
  { id: "c6", platform: "Instagram", preview: "Hook formula: pain point + hard number + bold promise in under 4 seconds.", likes: 7300, shares: 960, comments: 204, viralScore: 8.9, nicheTag: "#AI" },
  { id: "c7", platform: "X", preview: "I audited 100 startup reels. 76% failed in the first 2 seconds.", likes: 1710, shares: 390, comments: 145, viralScore: 8.4, nicheTag: "#founders" },
  { id: "c8", platform: "YouTube", preview: "From script to shoot day: our repeatable founder video workflow.", likes: 5400, shares: 750, comments: 300, viralScore: 8.5, nicheTag: "#storytelling" },
  { id: "c9", platform: "LinkedIn", preview: "Why your editor should be in strategy meetings, not just post-production.", likes: 990, shares: 180, comments: 49, viralScore: 8.1, nicheTag: "#business" },
  { id: "c10", platform: "Instagram", preview: "POV: your startup finally figures out content-market fit.", likes: 11200, shares: 1400, comments: 410, viralScore: 9.2, nicheTag: "#founders" },
  { id: "c11", platform: "X", preview: "The best content strategy is often a calendar, not a brainstorm.", likes: 1350, shares: 260, comments: 97, viralScore: 7.9, nicheTag: "#business" },
  { id: "c12", platform: "YouTube", preview: "Live teardown of top SaaS founder intros and why they convert.", likes: 4800, shares: 620, comments: 260, viralScore: 8.3, nicheTag: "#AI" },
];

export const tweetTemplates: TweetTemplate[] = [
  { id: "tt1", type: "Shitpost", preview: "Most startup content is a slide deck with background music and I am tired of pretending it is not.", prediction: "2.1K engagements" },
  { id: "tt2", type: "Thread Starter", preview: "I spent Rs 50L on video production. Here is what I learned (thread)", prediction: "3.6K engagements" },
  { id: "tt3", type: "Meme", preview: "Expectation: one viral reel. Reality: 47 drafts and one coffee overdose.", prediction: "1.4K engagements" },
  { id: "tt4", type: "Insight", preview: "If your founder cannot explain the business in 20 seconds, no ad spend can save it.", prediction: "1.8K engagements" },
  { id: "tt5", type: "Contrarian", preview: "You do not need a CMO first. You need content consistency first.", prediction: "2.9K engagements" },
  { id: "tt6", type: "Checklist", preview: "Before posting: hook, proof, CTA, subtitles, first comment.", prediction: "1.5K engagements" },
  { id: "tt7", type: "Story", preview: "Our client went from 0 to 14 inbound leads in 3 weeks with founder clips.", prediction: "2.0K engagements" },
  { id: "tt8", type: "Build in Public", preview: "We are testing 4 hook styles this week. I will share the winner Friday.", prediction: "1.3K engagements" },
  { id: "tt9", type: "Data Drop", preview: "Posts with a number in first 8 words got 31% higher saves in our dataset.", prediction: "2.4K engagements" },
  { id: "tt10", type: "One-liner", preview: "Content is not branding. Content is distribution.", prediction: "1.2K engagements" },
  { id: "tt11", type: "Opinion", preview: "If every post sounds corporate, your audience will scroll like it is spam.", prediction: "1.7K engagements" },
  { id: "tt12", type: "Framework", preview: "Hook -> Problem -> Proof -> Offer. Run this for 30 days.", prediction: "2.2K engagements" },
  { id: "tt13", type: "Question", preview: "What is one startup content myth you no longer believe?", prediction: "1.1K engagements" },
  { id: "tt14", type: "Hot Take", preview: "Most B2B videos are too clean and that is exactly why they underperform.", prediction: "2.5K engagements" },
  { id: "tt15", type: "Mini Thread", preview: "3 edits that made our watch time jump this month: 1) pattern interrupt 2) kinetic text 3) tighter endings", prediction: "2.8K engagements" },
];

export const tweetQueue: TweetQueueItem[] = [
  { id: "q1", time: "8:00 AM", text: "Hot take about AI video editing", status: "Scheduled" },
  { id: "q2", time: "10:00 AM", text: "Thread on client acquisition", status: "Scheduled" },
  { id: "q3", time: "12:00 PM", text: "Meme post", status: "Draft" },
  { id: "q4", time: "2:00 PM", text: "", status: "Empty" },
  { id: "q5", time: "4:00 PM", text: "Case study: 30-day content sprint", status: "Scheduled" },
  { id: "q6", time: "6:00 PM", text: "Founder one-liner on distribution", status: "Draft" },
  { id: "q7", time: "8:00 PM", text: "", status: "Empty" },
];

export const linkedInPosts: LinkedInPost[] = [
  { id: "li1", author: "Ankit B", headline: "SaaS Growth Advisor", preview: "We replaced polished corporate videos with honest founder updates and demos jumped 38%.", reactions: 1200, comments: 184, reposts: 95 },
  { id: "li2", author: "Neha S", headline: "Brand Strategist", preview: "A repeatable content system beats random creativity every quarter.", reactions: 980, comments: 122, reposts: 61 },
  { id: "li3", author: "Ravi K", headline: "Founder, OpsFlow", preview: "Why startup teams should treat video like sales collateral.", reactions: 1450, comments: 233, reposts: 109 },
  { id: "li4", author: "Meenal T", headline: "Content Lead", preview: "The first five seconds of your reel decide 80% of your outcomes.", reactions: 840, comments: 88, reposts: 47 },
  { id: "li5", author: "Varun P", headline: "B2B Marketer", preview: "We tested 27 hooks in 14 days. Here is what worked.", reactions: 1110, comments: 152, reposts: 74 },
  { id: "li6", author: "Shivani G", headline: "Founder Coach", preview: "Your team does not need more content ideas. It needs better constraints.", reactions: 930, comments: 97, reposts: 53 },
  { id: "li7", author: "Aditya N", headline: "Startup Operator", preview: "How we built a weekly content ritual that survived product chaos.", reactions: 790, comments: 69, reposts: 40 },
  { id: "li8", author: "Rhea M", headline: "Creative Director", preview: "Brand consistency does not mean visual sameness.", reactions: 670, comments: 75, reposts: 36 },
  { id: "li9", author: "Kunal J", headline: "Growth Consultant", preview: "In B2B, comments are often a better signal than likes.", reactions: 560, comments: 81, reposts: 29 },
  { id: "li10", author: "Pallavi R", headline: "Marketing Lead", preview: "One founder story per week transformed our hiring pipeline.", reactions: 1050, comments: 141, reposts: 66 },
];

export const activityFeed: ActivityItem[] = [
  { id: "a1", type: "invoice", text: "Invoice #INV-024 sent to Freshworks", timestamp: "2 hours ago" },
  { id: "a2", type: "lead", text: "New lead: Rahul from ScaleUp AI replied to cold email", timestamp: "5 hours ago" },
  { id: "a3", type: "delivery", text: "Reel delivered to client Zomato Creators", timestamp: "Yesterday" },
  { id: "a4", type: "payment", text: "Payment received: Rs 1,50,000 from BrightPath", timestamp: "Yesterday" },
  { id: "a5", type: "content", text: "LinkedIn post scheduled: Why founders need video", timestamp: "Today 6 PM" },
  { id: "a6", type: "project", text: "Freshworks Q1 Brand Reel moved to Review", timestamp: "1 day ago" },
  { id: "a7", type: "invoice", text: "Reminder sent for INV-028 to Freshworks", timestamp: "1 day ago" },
  { id: "a8", type: "lead", text: "Meeting booked with TechVentures for Mar 20", timestamp: "2 days ago" },
  { id: "a9", type: "delivery", text: "ScaleUp AI hiring ad final cut delivered", timestamp: "2 days ago" },
  { id: "a10", type: "payment", text: "Cred Creators settled final invoice", timestamp: "3 days ago" },
  { id: "a11", type: "content", text: "X thread auto-generated from case study", timestamp: "3 days ago" },
  { id: "a12", type: "project", text: "Notion India workspace tips shoot confirmed", timestamp: "3 days ago" },
  { id: "a13", type: "invoice", text: "Draft invoice created for UrbanClap add-on", timestamp: "4 days ago" },
  { id: "a14", type: "lead", text: "FinLeap opened campaign email", timestamp: "4 days ago" },
  { id: "a15", type: "delivery", text: "BrightPath launch teaser approved", timestamp: "4 days ago" },
  { id: "a16", type: "payment", text: "Notion India payment received", timestamp: "5 days ago" },
  { id: "a17", type: "content", text: "Instagram script generated for founder hook", timestamp: "5 days ago" },
  { id: "a18", type: "project", text: "UrbanClap customer proof reel moved to Shooting", timestamp: "5 days ago" },
  { id: "a19", type: "invoice", text: "Overdue alert triggered for ScaleUp AI", timestamp: "6 days ago" },
  { id: "a20", type: "lead", text: "AstraX marked as Won after intro call", timestamp: "6 days ago" },
  { id: "a21", type: "content", text: "YouTube trend card saved as template", timestamp: "1 week ago" },
];

export const revenueTrend = [
  { month: "Oct", value: 9.8 },
  { month: "Nov", value: 11.2 },
  { month: "Dec", value: 12.1 },
  { month: "Jan", value: 11.8 },
  { month: "Feb", value: 12.45 },
  { month: "Mar", value: 13.2 },
];

export const projectStatusBreakdown = [
  { name: "Shooting", value: 3 },
  { name: "Editing", value: 5 },
  { name: "Delivered", value: 12 },
  { name: "Follow-up", value: 2 },
];
